### ISSUE TITLE
Please ... 5.4.8 support !!!

### ISSUE THREAD

**Issue by Cubansephiroth** [anonymous33rus/wowbattlenet#1]
This is not really an issue and reading your post in Ace-web this will be implemented maybe in the future but this is a reminder that 5.4.8 support will be great.

Thanks for your awesome work.

**Comment by anonymous33rus** [comment]
Soon, support will be added for earlier versions (3.3.5, 4.3.4, 5.4.8)

Wait for version v1.2.9-alpha

**Comment by anonymous33rus** [comment]
v1.2.8-alpha
- Added registration for older versions
- In the admin panel added the ability to verify versions of the site
